### ISSUE TITLE
Cannot find module './react-native' from 'env.js'

### ISSUE THREAD

**Issue by stereodenis** [apentle/react-native-babel-jest#4]
```
./node_modules/.bin/jest

Cannot find module './react-native' from 'env.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/react-native-babel-jest/env.js:17:30)
```

**Comment by stereodenis** [comment]
@doanndd

**Comment by doanndd** [comment]
Thank you for reporting. I have been changed require command to './react-native/index' and update to version 0.2.1. Please download new code.
